### ISSUE TITLE
do, das, dedi, datum

### ISSUE THREAD

**Issue by PhVerkerk** [biblissima/collatinus#10]
Pour une raison obscure, le a des formes de do, dare est presque toujours bref, contrairement à celui d'amo, amare qui est presque toujours long. Il reste long dans das (indicatif présent) et da (impératif présent), ainsi que dans tous les cas où il est entravé : dant, dantur [...], dans, dantis et autres dandus. 
Dans Collatinus 10.2 nous avions un patch qui reconnaissait les composés de do, dare. Dans Collatinus 11, il doit avoir son propre modèle.

**Comment by ycollatin** [comment]
dérivé de amo. D'accord.

**Comment by ycollatin** [comment]
J'ai inséré un modele:do, pere:amo, redéfini les désinence d'indicatif présent, et assigné dans lemmes.la le modèle do au lemme do. Je n'ai pas cherché tous les cas d'abrègement du a. Tu les connais, Philippe ? Tu ajoutes ou j'ajoute ?

**Comment by PhVerkerk** [comment]
Tous les premiers a des formes en da\* sont brefs sauf s'ils sont 
entravés et les deux cas spéciaux das et da qui restent longs. Donc
dămŭs... dăbŏ, dăbĭs... dărĕm...
Le plus simple est que tu le fasses.

Ph.

**Comment by ycollatin** [comment]
Le 28 avril 2016, à 01h13, PhVerkerk écrivit :

> Tous les premiers a des formes en da\* sont brefs sauf s'ils sont 
> entravés et les deux cas spéciaux das et da qui restent longs. Donc
> dămŭs... dăbŏ, dăbĭs... dărĕm...
> Le plus simple est que tu le fasses.

```
Je vais m'y mettre. Avec toutes les issues qui sont
```

arrivées, je commence à me demander quand je pourrai me

## remettre à ma syntaxe.

```
                    Yves
```

**Comment by ycollatin** [comment]
Le 28 avril 2016, à 10h22, Yves Ouvrard écrivit :

> Le 28 avril 2016, à 01h13, PhVerkerk écrivit :
> 
> > Tous les premiers a des formes en da\* sont brefs sauf s'ils sont 
> > entravés et les deux cas spéciaux das et da qui restent longs. Donc
> > dămŭs... dăbŏ, dăbĭs... dărĕm...
> > Le plus simple est que tu le fasses.
> 
> ```
> Je vais m'y mettre. Avec toutes les issues qui sont
> ```
> 
> arrivées, je commence à me demander quand je pourrai me
> remettre à ma syntaxe.

```
J'ai quand même des doutes. Je vois mal l'imparfait
```

dabam avec un brève : dăbam. OK pour dăre, dărem, etc.

## 

```
                    Yves
```

**Comment by PhVerkerk** [comment]
Plus très lisible, mais c'est dans Quicherat (le gros, p. 24).

Ph.

**Comment by ycollatin** [comment]
Le 28 avril 2016, à 03h50, PhVerkerk écrivit :

> Plus très lisible, mais c'est dans Quicherat (le gros, p. 24).
>     Juste. carmina-latina.com le sande en brèves.

## 

```
                    Yves
```

**Comment by eroux** [comment]
idem : est-ce que ça a été changé ?

**Comment by PhVerkerk** [comment]
Oui.
