### ISSUE TITLE
reconnaissance de æ et œ

### ISSUE THREAD

**Issue by eroux** [biblissima/collatinus#11]
Ce serait pratique si Collatinus pouvait transformer automatiquement æ en ae et œ en oe, pour pouvoir analyser des textes médiévaux directement

**Comment by ycollatin** [comment]
Fait, deux replace en tête de lemmatise().

**Comment by eroux** [comment]
Je rouvre, au vu du problème des majuscules, et du possible déplacement, voir [ce commentaire](https://github.com/biblissima/collatinus/issues/17#issuecomment-215383202)

**Comment by PhVerkerk** [comment]
En lisant deramise, j'ai repensé aux sauvages qui écrivent Vlixes pour 
Ulysse... Vlixes était reconnu dans la 10.3, pas dans la 11 d'hier. Cela 
pose un vrai problème avec le comptage des v. Je ne sais plus comment 
nous l'avions résolu.

**Comment by eroux** [comment]
Pour le V majuscule, il n'est pas "déramisé" dans C11, la ligne est
commentée... Yves vous vous rappelez pourquoi ?

**Comment by ycollatin** [comment]
Le 28 avril 2016, à 07h30, Elie Roux écrivit :

> Pour le V majuscule, il n'est pas "déramisé" dans C11, la ligne est
> commentée... Yves vous vous rappelez pourquoi ?

```
Réponse provisoire (il faut que je m'y replonge) : Parce
```

que le V majuscule est ambigu : c'est tantôt un vrai V,
tantôt une graphie du U utilisée par certains textes et la

## plupart du temps par les inscriptions.

```
                    Yves
```
