### ISSUE TITLE
possibilité d'enlever les accents

### ISSUE THREAD

**Issue by eroux** [biblissima/collatinus#12]
Collatinus 10.3 offre la possibilité de débarasser un texte de ses accents (aigus, breve macron), ce qui est assez pratique. J'aurais tendance à le faire automatiquement (comme pour œ et æ), mais je vous laisse voir, dans la 10.3 c'est une action dans le menu.

**Comment by PhVerkerk** [comment]
L'action dans le menu est un choix, car une façon souvent utilisée pour importer un texte est le copier-coller. Si on a récupéré un texte accentué, il peut être utile d'ôter les accents, par une commande.
Je pense qu'un copier-coller de :
void fenestra::oteDiac()
{
    QString contenu = EditLatin->toPlainText ();
    contenu = contenu.normalized(QString::NormalizationForm_D,QChar::currentUnicodeVersion());
    contenu.remove("\u0301");
    contenu.remove("\u0306");
    contenu.remove("\u0304");
    EditLatin->setPlainText(contenu);
}
fera l'affaire.

**Comment by ycollatin** [comment]
Le 28 avril 2016, à 03h36, PhVerkerk écrivit :

> void fenestra::oteDiac()
>     Tu travailles encore sur C10 ?
> 
> ## fenestra n'existe plus dans C11.
> 
> ```
>                               Yves
> ```

**Comment by PhVerkerk** [comment]
Travaillais ! C'est ce que j'avais écrit il y a 15 jours. Mais il suffit 
probablement de remplacer fenestra par mainwindow (peut-être avec 
majuscule).

**Comment by ycollatin** [comment]
Le 28 avril 2016, à 05h22, PhVerkerk écrivit :

> Travaillais ! C'est ce que j'avais écrit il y a 15 jours. Mais il suffit 
> probablement de remplacer fenestra par mainwindow (peut-être avec 
> majuscule).

```
OK. D'accord pour nettoyer les ligatures æ et ½, et les
```

accents directement dans l'interface. Il faudra supprimer
mes deux lignes "replace..." au début de Lemmatiseur::lemmatise().

## 

```
                    Yves
```

**Comment by PhVerkerk** [comment]
Pas sûr que ce soit une bonne chose, car cela supprime la distinction 
possible entre Æneas et Aeneas.
Dans la 10.3, je ne l'ai pas fait.

**Comment by ycollatin** [comment]
Le 28 avril 2016, à 05h40, PhVerkerk écrivit :

> Pas sûr que ce soit une bonne chose, car cela supprime la
> distinction possible entre Æneas et Aeneas.
> Dans la 10.3, je ne l'ai pas fait.

```
Comme je n'ai pas suivi attentivement depuis le début,
```

je risque d'avoir mal compris. Ça voudrait dire que les
textes pratiquant la ligature Æ font la distinction avec
A+e, et écrivent Æneas pour Énée et Aeneas en début de
phrase pour l'acc. fém pl. de ăēneus ? Il y en a des exemples ?

```
Si oui, mieux vaut en effet placer dans deramise
```

les transformation Æ -> Āe et Ae -> Ae, le radical se

## chargeant de la scansion. J'ai besoin d'une mise à niveau.

```
                    Yves
```

**Comment by eroux** [comment]
Les textes liturgiques distinguent ær et aer par exemple oui (enfin je ne suis pas totalement sûr d'avoir bien compris votre question). Si vous prenez par exemple le [psaume 13](https://github.com/gregorio-project/latin-ecclesiatic-accents/blob/master/corpus/psalms/013.txt) vous verrez _lætábitur Israel_ (æ disphtongue, ae deux voyelles distinctes).

**Comment by eroux** [comment]
P.S.: diphtongue historique d'ailleurs, puisque _æ_ est prononcée _é_ en latin liturgique...

**Comment by ycollatin** [comment]
Le 28 avril 2016, à 06h20, Elie Roux écrivit :

> P.S.: diphtongue historique d'ailleurs, puisque _æ_ est
> prononcée _é_ en latin liturgique...

```
D'accord. Donc dans deramise(). Attendons l'imprimatur
```

## de Philippe.

```
                    Yves
```

**Comment by PhVerkerk** [comment]
Je pense que les transformation æ --> ae, Æ --> Ae, œ --> oe et Œ --> Oe 
ont leur place dans deramise. En ayant compté les v, æ et œ que le mot 
contient avant de déramiser. Voir début de Lexicum::corAnalyses de la 
10.3, mais je n'avais pas pensé à remonter les replace dans Ch::jviu.

**Comment by eroux** [comment]
je crée une branche `fix-12`, je propose de pousser les changements dedans, je vais en pousser quelques uns tout à l'heure

**Comment by eroux** [comment]
J'ai poussé deramise et le bout de code qui compte les v, æ et œ, par contre pour le reste du portage du code de la 10.3, il y a des choses qui vont trop loin pour que j'intervienne dessus sans tout casser... il y a par exemple `est_V_phage()` qui a l'air d'avoir besoin de certaines choses dans le format de la désinence, et je ne sais pas si ça a changé avec Collatinus-11 ni comment tester, du coup je préfère laisser @PhVerkerk  faire pour la suite...

**Comment by eroux** [comment]
(j'ai implémenté Ch:deAccent qui désaccentue une QString, la fonction n'est pas encore utilisée)

**Comment by eroux** [comment]
En fait ce serait pratique aussi d'enlever les trémas, j'en trouve assez souvent dans certains textes liturgiques : eleïson souvent, mais parfois aussi pour différencier les ae diphtongues des ae non-diphtongues (Israël par exemple). Il serait donc pratique de rajouter `U+0308` dans la liste des accents à enlever.

Aussi, je ne sais pas à quel niveau c'est bien de le faire, mais on trouve dans certains textes (pas spécialement liturgiques) ç et Ç en lieu et place de s et S (dans le Du Cange par exemple), peut-être qu'on peut rajouter ça à déramise ou à deaccent ? ou renommer deaccent en... je ne sais pas quoi ?
