### ISSUE TITLE
comptage des v, æ et œ.

### ISSUE THREAD

**Issue by PhVerkerk** [biblissima/collatinus#17]
Pour éviter de scander voluit en vŏlŭĭt (vōlvĭt), nous comptions les v dans la forme d'origine (éventuellement ramiste) pour ne pas proposer volvo comme lemmatisation de voluit. À partir du moment où on convertit les æ en ae, il faudrait le faire aussi pour ces diphtongues. Pas critique pour œ, mais peut éviter la confusion Æneas aeneas, comme pour voluit volvit.

**Comment by eroux** [comment]
C'est vrai, d'ailleurs dans https://github.com/biblissima/collatinus/commit/058a9abf257f7dc741b5b0bbf13b2ee2e8d14f8d il y a un problème qui est que les majuscules _Æ_ et _Œ_ restent... Et est-ce que cette opération n'aurait pas plutôt sans place dans `Ch::deramise` plutôt que dans `Lemmat::lemmatise` ?
