### ISSUE TITLE
illius

### ISSUE THREAD

**Issue by PhVerkerk** [biblissima/collatinus#19]
Dans 10.3, le 2e i d'illius était commun, comme dans le Cart-Grimal p. 36, §65. 
Maintenant, il est devenu bref.
Il faudrait probablement vérifier toutes les désinences...

**Comment by ycollatin** [comment]
Le 28 avril 2016, à 14h13, PhVerkerk écrivit :

> Dans 10.3, le 2e i d'illius était commun, comme dans le Cart-Grimal p. 36, §65. 
> Maintenant, il est devenu bref.
> Il faudrait probablement vérifier toutes les désinences...

```
Oui. J'ai écrit les à mesure que j'ajoutais les modèles,
```

## au lieu de les reprendre de C10. Je vais voir illius.

```
                    Yves
```

**Comment by ycollatin** [comment]
Le 28 avril 2016, à 14h13, PhVerkerk écrivit :

> Dans 10.3, le 2e i d'illius était commun, comme dans le Cart-Grimal p. 36, §65. 
> Maintenant, il est devenu bref.

```
C'est corrigé.
```

## 

```
                    Yves
```
