### ISSUE TITLE
déramisation de V ?

### ISSUE THREAD

**Issue by eroux** [biblissima/collatinus#21]
Pour l'instant, V n'est pas déramisé en U, cela pose un problème pour reconnaître Vlixes. La ligne est commentée dans Ch::deramise, il faudrait comprendre pourquoi

**Comment by ycollatin** [comment]
Le 29 avril 2016, à 01h48, Elie Roux écrivit :

> Pour l'instant, V n'est pas déramisé en U, cela pose un
> problème pour reconnaître Vlixes. La ligne est commentée
> dans Ch::deramise, il faudrait comprendre pourquoi

```
La méthode serait V + voyelle -> V et V + consonne -> U.
```

Il faudrait voir si cette règle n'a aucune exception, ou
suffisamment peu pour qu'on en fasse une liste. Il faudrait
donc chercher des exemples de U+voyelle, ou V+consonne. Et
comme il y a dans les titres et les inscriptions des mots
entièrement en majuscules, ça complique la recherche. Par
exemple, le relatif QVI (V+voyelle) doit devenir QUI, alors

## que VINCO doit reste VINCO.

```
                    Yves
```

**Comment by eroux** [comment]
Aucune exception dans le Gaffiot en tous cas... mais je ne comprend finalement pas trop le rapport avec deramise, qui est sensé justement déramiser et donc tout transformer en U... ? S'il n'y a pas d'exception à cette règle, ça veut dire qu'il n'y a aucune ambiguité justement, et donc qu'on peut transformer les V en U pour les recherches dans le lexique non ?

**Comment by PhVerkerk** [comment]
Le problème n'est probablement pas tant dans deramise que dans le 
comptage des V (quand il sera implémenté).
Il faut vérifier que ça ne crée pas de conflit avec lemmes.fr et, 
surtout, avec irregs.la (où la clef est non ramiste).

**Comment by ycollatin** [comment]
Le 29 avril 2016, à 02h49, PhVerkerk écrivit :

> Le problème n'est probablement pas tant dans deramise que dans le 
> comptage des V (quand il sera implémenté).
> Il faut vérifier que ça ne crée pas de conflit avec lemmes.fr et, 
> surtout, avec irregs.la (où la clef est non ramiste).

```
Merci Philippe. En tout cas, Vnelli (= Unelli) n'est pas
```

## reconnu, malgré la présence du lemme dans lemmes.la.

```
                    Yves
```
