### ISSUE TITLE
ille

### ISSUE THREAD

**Issue by PhVerkerk** [biblissima/collatinus#22]
Dans le modèle ille, la ligne "des:16,28,40:0:ī̆ŭs" était inutile, puisque le i du génitif est déjà commun dans le modèle "unus", qui est le père du modèle ille.
La ligne qui suit "des+:15,18,21,25,27,42:1:ūnc;ōc;ōscĭnĕ;āec;ānc;ōc" a des effets dévastateurs sur le tableau de flexion. Quand elle est commentée, j'obtiens un tableau de flexion qui ressemble à celui que je trouve dans le Cart-Grimal. Quand elle ne l'est pas, j'obtiens un accusatif masculin "īllūnc" et un ablatif "īllōc", conformes aux deux premiers items de la liste. Sauf que les formes normales "īllŭm" et "īllō" ont disparu. Comme si le "des+:" était interprété comme un "des:". 
Une erreur liée aux derniers merge ?

**Comment by PhVerkerk** [comment]
Vérifié aussi avec "infans" qui devrait avoir un double génitif pluriel en um et ium d'après la définition.
modele:infans
pere:fortis
des+:22,34,46:1:ŭm

**Comment by ycollatin** [comment]
```
Bonjour Philippe, bonjour Élie,
```

Le 30 avril 2016, à 13h41, PhVerkerk écrivit :

> Dans le modèle ille, la ligne "des:16,28,40:0:ī̆ŭs" était
> inutile, puisque le i du génitif est déjà commun dans le
> modèle "unus", qui est le père du modèle ille.
> La ligne qui suit
> "des+:15,18,21,25,27,42:1:ūnc;ōc;ōscĭnĕ;āec;ānc;ōc" a des
> effets dévastateurs sur le tableau de flexion. Quand elle
> est commentée, j'obtiens un tableau de flexion qui
> ressemble à celui que je trouve dans le Cart-Grimal. Quand
> elle ne l'est pas, j'obtiens un accusatif masculin
> "īllūnc" et un ablatif "īllōc", conformes aux deux
> premiers items de la liste. Sauf que les formes normales
> "īllŭm" et "īllō" ont disparu. Comme si le "des+:" était
> interprété comme un "des:". 
> Une erreur liée aux derniers merge ?

```
C'est sérieux en tout cas. Écraser les désinences
```

héritées n'est pas le but de des+. Soit il y a une rupture
dans la chaîne d'héritage (doct-ŭm est l'ancêtre), soit
l'interpréteur a un bogue. Je vais chercher.

## 

```
                    Yves
```

**Comment by PhVerkerk** [comment]
J'ai ré-essayé avec la version précédente (avant les merge et la normalisation du format) et le résultat est le même : "des+" écrase les désinences du père (au moins pour ille). 

Le Dimanche 1 Mai 2016 08:00 CEST, Yves Ouvrard notifications@github.com a écrit:

**Comment by ycollatin** [comment]
Le 30 avril 2016, à 23h07, PhVerkerk écrivit :

> J'ai ré-essayé avec la version précédente (avant les merge
> et la normalisation du format) et le résultat est le même
> : "des+" écrase les désinences du père (au moins pour
> ille). 

```
Oui. Je viens aussi de le constater. J'ai commencé le
```

## débogage.

```
                    Yves
```

**Comment by ycollatin** [comment]
Le 30 avril 2016, à 13h45, PhVerkerk écrivit :

> Vérifié aussi avec "infans" qui devrait avoir un double génitif pluriel en um et ium d'après la définition.
> modele:infans
> pere:fortis
> des+:22,34,46:1:ŭm

```
Trouvé la cause : la regexp qui éclate la ligne de
```

données est incapable de distinguer "des" et "des+". Je vais
essayer de la corriger. Sinon, il faudra changer la clé des+

## en "desp" par exemple.

```
                    Yves
```

**Comment by ycollatin** [comment]
Le 30 avril 2016, à 13h41, PhVerkerk écrivit :

> Dans le modèle ille, la ligne "des:16,28,40:0:ī̆ŭs" était
> inutile, puisque le i du génitif est déjà commun dans le
> modèle "unus", qui est le père du modèle ille.

```
Corrigé : Je me demande ce que venait faire
```

l'instruction 

l.remove('+');

vers la ligne 112 de modele.cpp. Elle est commentée, pour
suppression si le bogue est considéré comme fixé.

## 

```
                    Yves
```

**Comment by eroux** [comment]
Il n'y a pas de référence à ce ticket dans des commits, mais de ce que je comprend des échanges on peut le fermer ?

**Comment by PhVerkerk** [comment]
Oui, je pense que ça a été fait en même temps que les ajouts de 
quantités dans modele.la

Ph.

**Comment by eroux** [comment]
ok!

**Comment by ycollatin** [comment]
Le 3 mai 2016, à 03h04, Elie Roux écrivit :

> Closed #22.
> 
> ##     Merci.
> 
> ```
>                     Yves
> ```
