### ISSUE TITLE
Poesis est présent comme modèle. Pas comme lemme

### ISSUE THREAD

**Issue by PonteIneptique** [biblissima/collatinus#33]
Bonjour à vous,
En transférant le code en python, j'ai découvert que Poesis était présent comme modèle mais absent de lemmes.la. Peut-être ai-je raté une ligne de code mais il me semble que cela devrait y être ?

**Comment by ycollatin** [comment]
```
Bonjour Thibault, bonjour tous,
```

Le 26 septembre 2016, à 06h15, Thibault Clérice écrivit :

> En transférant le code en python, j'ai découvert que
> Poesis était présent comme modèle mais absent de
> lemmes.la. Peut-être ai-je raté une ligne de code mais il
> me semble que cela devrait y être ?

```
Oui. Si tu reprends Collatinus 11, Tu peux l'ajouter :
```

Dans bin/data/lemmes.la :

pŏēsis|poesis|pŏēs||is, f.

Dans bin/data/lemmes.fr :

poesis:poème, poésie

... et dans bin/data/modeles.la, il faut corriger

modele:poesis
pere:ciuis
des+:3,4:1:ĭn,ĭm;ĕŏs

... Mais si tu utilises la version 10, c'est complètement
différent !

## 

```
                    Yves
```

**Comment by PhVerkerk** [comment]
Bonjour à tous,

Poesis est dans l'extension du lexique ! Certes avec le modèle ciuis >:o.

On peut avoir envie de le mettre dans lemmes.la, mais dans ce cas, il 
faut le supprimer de lem_ext.la. C'est un des handicaps de cette 
séparation entre lexique courant (et humainement établi) et le reste 
(pas vérifié).

On parle depuis longtemps d'un gestionnaire de lexiques qui permettrait 
à l'utilisateur de transférer un mot qu'il rencontre fréquemment de 
l'extension au lexique courant (ou l'inverse). Et de se construire un 
lexique personnel...

À bientôt,

```
 Philippe.
```

**Comment by PonteIneptique** [comment]
Bonjour à vous deux,
merci pour vos prompts retours. Je note pour la question de lexique ext que je n'ai pas encore testé :)
Pour le moment, je vous ai envoyé une correction en PR. Vérifiez les quantités mais il me semble que c'est correct. Dès que mon morceau de code est prêt, je vous le partage ;)
