### ISSUE TITLE
Lemma inconnus sur le corpus de Proiel [PyCollatinus]

### ISSUE THREAD

**Issue by PonteIneptique** [biblissima/collatinus#49]
D'après PyCollatinus, les formes et lemmes suivant-e-s sont inconnu-e-s : 

| forme | lemme |
| ----- | ----- |
| Abiud | Abiud |
| absorta | absorbeo |
| Acheldemach | Acheldemach |
| Achim | Achim |
| Acutilianam | Acutilianus |
| Acutiliano | Acutilianus |
| Adae | Adam |
| adduc | adduco |
| adherebit | adhaereo |
| adherentes | adhaereo |
| adheret | adhaereo |
| adhesit | adhaereo |
| adhortere | adhortor |
| Adiatunnus | Adiatunnus |
| adpropinquassent | appropinquo |
| adpropinquasset | appropinquo |
| adsciscunt | ascisco |
| adspirante | aspiro |
| adspirare | aspiro |
| adsuefacti | assuefacio |
| adtractent | attrecto |
| Aeduae | Haeduus |
| afuturum | absum |
| Agabus | Agabus |
| alligasset | alligo |
| Allobrogas | Allobroges |
| amethistus | amethistus |
| Amiano | Amianus |
| Amon | Amon |
| Amos | Amos |
| Amphipolim | Amphipolis |
| Apellen | Apelles |
| Apenas | Apenas |
| apocalypsin | apocalypsis |
| Apollonidensem | Apollonidensis |
| April | April |
| Araus | Araus |
| Arfaxat | Arfaxat |
| Ariopagi | Ariopagus |
| Ariopagita | Ariopagita |
| Ariopagitae | Ariopagita |
| Ariopagitis | Ariopagita |
| Ariopago | Ariopagus |
| Ariopagum | Ariopagus |
| Atuatucam | Aduatuca |
| aventu | adventus |
| Azor | Azor |
| Bar | Bar |
| Barsabban | Barsabban |
| Bartholomeum | Bartholomeus |
| Bartholomeus | Bartholomeus |
| Bartimeus | Bartimeus |
| Beroensis | Beroensis |
| Bethfage | Bethfage |
| bithalassum | bithalassus |
| Blasto | Blastus |
| Caiapha | Caiaphas |
| Caiaphae | Caiaphas |
| Caiaphan | Caiaphas |
| Caiaphas | Caiaphas |
| Cananeum | Cananeus |
| Cananeus | Cananeus |
| carcedonius | carcedonius |
| Catamantaloedis | Catamantaloedes |
| catecizat | catecizo |
| catecizatur | catecizo |
| Catuvolcus | Catuvolcus |
| CCCC | CCCC |
| CCIↃↃ | CCIↃↃ |
| Cencris | Cenchreae |
| Cephae | Cephas |
| Cephas | Cephas |
| chananea | chananeus |
| chirografum | chirographum |
| Cho | Cho |
| chrysolitus | chrysolitus |
| chrysoprassus | chrysoprassus |
| Chuza | Chuza |
| Cimberium | Cimberius |
| clamydem | clamys |
| Cleopae | Cleopa |
| Cleopas | Cleopas |
| Coctia | Coctius |
| cofini | cofinus |
| cofinos | cofinus |
| cogitaramus | cogito |
| cognoram | cognosco |
| cognoris | cognosco |
| cognoro | cognosco |
| cognosse | cognosco |
| colleximus | colligo |
| collexistis | colligo |
| comesationes | comesatio |
| comesationibus | comesatio |
| conbuserunt | comburo |
| conlocaram | colloco |
| conlocarat | colloco |
| consequerere | consequor |
| consuessem | consuesco |
| consuessent | consuesco |
| contemnabamus | contemno |
| Corazain | Corazain |
| corban | corban |
| corbanan | corbanas |
| Coriosolitas | Coriosolitae |
| Coriosolites | Coriosolites |
| cristallum | cristallus |
| cuicui | quisquis |
| cyrenei | Cyrenaeus |
| Cyreneum | Cyrenaeus |
| cyreneum | Cyrenaeus |
| Danihelo | Danihelus |
| D̅C̅C̅C̅ | D̅C̅C̅C̅ |
| Dec | Dec |
| Decembr | Decembr |
| Decembr. | Decembr. |
| decressent | decerno |
| decucurrerunt | decurro |
| decucurrit | decurro |
| dicundo | dico |
| didragma | didragma |
| difficillimis | difficilis |
| Dionisius | Dionisius |
| Divico | Divico |
| duodetreginta | duodetreginta |
| earundem | is |
| Eber | Eber |
| ecquae | ecquis |
| ecquod | ecqui |
| Efrem | Efrem |
| elemosynam | elemosyna |
| elemosynas | elemosyna |
| Eliachim | Eliachim |
| Eliud | Eliud |
| Elymas | Elymas |
| Emmanuhel | Emmanuhel |
| encenia | encenium |
| Enos | Enos |
| Epafrodito | Epafroditus |
| Epafroditum | Epafroditus |
| Ephaenetum | Ephaenetus |
| Epicratem | Epicrates |
| eppheta | eppheta |
| Equotutico | Equotuticus |
| Esli | Esli |
| Esrom | Esrom |
| Esuvios | Esuvii |
| Eufrate | Eufrates |
| Eufraten | Eufrates |
| Euhodiam | Euhodia |
| exiebant | exeo |
| exiebat | exeo |
| exilierunt | ex(s)ilio |
| expiscere | expiscor |
| extinguntur | ex(s)tinguo |
| faciundi | facio |
| facteon | facio |
| fantasma | fantasma |
| Febr | Febr |
| Februar | Februar |
| ficu | ficus |
| Filologum | Filologus |
| Flegonta | Flegon |
| Foenicen | Foenicen |
| Fontius | Fontius |
| Frygiam | Phrygia 
| Funisulanus | Funisulanus |
| Gabrihel | Gabrihel |
| Gad | Gad |
| Gamalihel | Gamalihel |
| gazofilacio | gazophylacium |
| gazofilacium | gazophylacium |
| Gennesar | Gennesar |
| Gnaio | Gnaius |
| Gnaium | Gnaeus |
| Gog | Gog |
| Gomorraeorum | Gomorraei |
| grabatto | grabattus |
| grabattum | grabattus |
| Haeduae | Aeduus |
| haurierant | haurio |
| hedis | haedus |
| hedos | haedus |
| Helia | Helias |
| Heliae | Helias |
| Heliam | Helias |
| Heliseo | Heliseus |
| Helmadam | Helmadam |
| Heloi | Heloi |
| Helonius | Helonius |
| hereticum | haereticus |
| Hermagedon | Hermagedon |
| Hermonis | Hermo |
| Hierichum | Hiericho |
| Hierusalem | Hierosolyma |
| hii | hic |
| honorificentior | honorificus |
| honorificentius | honorifice |
| Iannae | Iannae |
| Ianuar | Ianuar |
| Iared | Iared |
| idolatriae | idolatria |
| idolatris | idolatra |
| Idumea | Idumea |
| iiii | iiii |
| IIII | IIII |
| implesset | impleo |
| ingemescens | ingemesco |
| ingemescimus | ingemesco |
| ingemescit | ingemesco |
| inirentur | ineo |
| inlustrarunt | illustro |
| inquiens | inquam |
| insuflavit | insufflo |
| introduc | introduco |
| Ioda | Ioda |
| Iohanna | Iohanna |
| Iohel | Iohel |
| Ioram | Ioram |
| Iordanen | Iordanes |
| Iorim | Iorim |
| Iosech | Iosech |
| iretur | eo |
| Israhelita | Israelitae |
| Israhelitae | Israelitae |
| israhelitae | Israelitae |
| Itureae | Iturea |
| Kal. | Kal. |
| Kal.Iunias | Kal.Iunias |
| Kal.Maias | Kal.Maias |
| Kaldiem | Kaldiem |
| Kalend | Kalend |
| KalMaias | KalMaias |
| laguenam | lagona |
| Lamech | Lamech |
| Levin | Levi |
| Lingonas | Lingones |
| linuit | lino |
| longevus | longevus |
| Luteciam | Lutecia |
| Lybiae | Lybia |
| Maath | Maath |
| Magog | Magog |
| Maias. | Maias. |
| Malchus | Malchus |
| Malelehel | Malelehel |
| Manaen | Manaen |
| manufacta | manufactus |
| manufactis | manufactus |
| maranatha | maranatha |
| Matinio | Matinius |
| Matinium | Matinius |
| Matthan | Matthan |
| Matthat | Matthat |
| Matthata | Matthata |
| Matthathiae | Matthathias |
| Melchi | Melchi |
| mementote | meminisse |
| Menna | Menna |
| Mennianorum | Mennianus |
| Menophili | Menophilus |
| Menturnensis | Minturnensis |
| Menturnis | Minturnae |
| Michahel | Michael |
| Militene | Militene |
| miscite | misceo |
| Moeragene | Moeragenes |
| Moeragenes | Moeragenes |
| molentes | molo |
| n | ne |
| Nachor | Nachor |
| Naggae | Naggae |
| Nammeius | Nammeius |
| Nasuam | Nasua |
| Nathanahel | Nathanahel |
| Naum | Naum |
| necessariora | necessarius |
| neglegant | neglego |
| neglegemus | neglego |
| neglegenda | neglego |
| neglegere | neglego |
| Neman | Neman |
| Nepthalim | Nepthalim |
| ninevitae | Ninevitae |
| Ninevitis | Ninevitae |
| Non. | Non. |
| norim | nosco |
| norunt | nosco |
| nosset | nosco |
| Nov. | Nov. |
| Novembr | Novembr |
| Novembr. | Novembr. |
| Numestio | Numestius |
| Numestium | Numestius |
| Octobr | Octobr |
| octogenti | octogenti |
| Omega | omega |
| Onesifori | Onesiforus |
| optaramus | opto |
| Orcyniam | Orcynia |
| orfanos | orphanus |
| Orgetoricem | Orgetorix |
| Osaces | Osaces |
| osanna | osanna |
| Pamphilia | Pamphylia |
| Pamphiliae | Pamphylia |
| Pamphiliam | Pamphylia |
| paterfamiliae | paterfamiliae |
| pedagogo | paedagogus |
| pedagogorum | paedagogus |
| pedagogus | paedagogus |
| perduc | perduco |
| perfodiri | perfodio |
| pertransiebant | pertranseo |
| pertransiet | pertranseo |
| pervelim | pervolo |
| petum | impetus |
| Phaetho | Phaetho |
| Phalec | Phalec |
| Phanuhel | Phanuhel |
| Pilius | Pilius |
| pinguidinis | pinguido |
| Plotia | Plotius |
| Pontidia | Pontidia |
| praesciit | praescio |
| prendiderunt | pr(eh)endo |
| prendidistis | pr(eh)endo |
| prohoemiis | prooemium |
| Ptianii | Ptanii |
| Ptolomaeum | Ptolomaeus |
| Ptolomaida | Ptolemais |
| quandam | quidam |
| quartadecima | quartusdecimus |
| quartamdecimam | quartusdecimus |
| quendam | quidam |
| quidlibet | quilibet |
| Quint | Quint |
| Quint. | Quint. |
| quintodecimo | quintusdecimus |
| quodque | quisque |
| rabboni | rabboni |
| Rachab | Rachab |
| Ragau | Ragau |
| Rama | Rama |
| Rantius | Rantius |
| repetisset | repeto |
| Resa | Resa |
| sabacthani | sabacthani |
| Sabaoth | Sabaoth |
| Sabim | Sabis |
| Saddoc | Saddoc |
| Salathihel | Salathihel |
| Salim | Salim |
| Salmon | Salmon |
| sapphyrus | sapphyrus |
| sardonix | sardonix |
| Sareptha | Sareptha |
| Scaldim | Scaldis |
| Scariotes | Scarioth |
| Scarioth | Scarioth |
| Scariotis | Scarioth |
| Scevae | Sceva |
| scisma | schisma |
| semicintia | semicintium |
| Sept | Sept |
| Seruch | Seruch |
| Sext. | Sext. |
| Sextil | Sextil |
| Sextil. | Sextil. |
| Sibusates | Sibusates |
| Sopolidis | Sopolis |
| sordem | sordes |
| Sosthenen | Sosthenes |
| Sotiatium | Sotiates |
| Stachyn | Stachys |
| Sufenas | Sufenas |
| Sychar | Sychar |
| Symeon | Symeon |
| Syntychen | Syntyche |
| Syrtim | Syrtis |
| Tadiana | Tadianus |
| Tadiano | Tadianus |
| taedeat | taedet |
| taedebat | taedet |
| taedere | taedet |
| taederet | taedet |
| Thaddeum | Thaddeus |
| Thaddeus | Thaddeus |
| Thare | Thara |
| Thyillus | Thyillus |
| Timei | Timeus |
| transiebat | transeo |
| transient | transeo |
| transiri | transeo |
| tremefactus | tremefacio |
| Troucillum | Troucillus |
| Tryfenam | Tryphaena |
| Tryfosam | Tryphosa |
| tunditores | tunditor |
| unianimiter | unianimiter |
| utervis | utervis |
| Vedianas | Vedianus |
| Verucloetius | Verucloetius |
| vetati | veto |
| viiii | viiii |
| Voccionis | Voccio |
| Volcatium | Volcatius |
| Xenocratem | Xenocrates |
| xiiii | xiiii |
| Zaccharia | Zaccharias |
| Zacchariae | Zaccharias |
| Zacchariam | Zaccharias |
| Zaccharias | Zaccharias |
| Zacchee | Zaccheus |
| Zaccheus | Zaccheus |
| Zostera | Zostera |

**Comment by PonteIneptique** [comment]
Un bug d'une librairie externe à collatinus transformait les y courts en u (à la place de y) dans `atone` ce qui supprime quelques unes des erreurs sus-citées

**Comment by PhVerkerk** [comment]
Ce n'est pas un bug : le y-bref (avec le signe diacritique "breve") n'existe pas dans unicode et nous l'avons codé par le "SHORT-U" cyrillique (U+045E). Si on utilise une routine qui ôte les diacritiques, il semble logique d'obtenir un "u", même si graphiquement ça n'a rien à voir.

**Comment by PonteIneptique** [comment]
Je viens d'avoir cette réponse de la personne responsable de la librairie :)

**Comment by PonteIneptique** [comment]
J'ai mis à jour la liste après la correction du bug PyCollatinus y/u et de la mise à jour du vocabulaire de la règle de Saint Benoit (donc pycollatinus==0.1.2) : 449 lemmes uniques inconnus pour 849 formes
