### ISSUE TITLE
complura

### ISSUE THREAD

**Issue by wehro** [biblissima/collatinus#52]
The usual neuter form of *complures* is *complura*, but this form is not recognized by *Collatinus*.

**Comment by PhVerkerk** [comment]
I have added complura in irregs.la. Although it looks a regular form, it is incompatible with the genitive complurium . The regular form compluria exists also (less frequent : 2 occurrences in the texts lemmatized by the LASLA, against 16 occ. of complura ). The Lewis & Short gives : " com-plūres ( conp- ), a , and (mostly ante-class.) ia ; gen. ium". 
The up-date of this file irregs.la should solve the issue 52. 
Ph. 


De: "wehro" <notifications@github.com> 
À: "biblissima/collatinus" <collatinus@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Envoyé: Mercredi 14 Novembre 2018 00:05:44 
Objet: [biblissima/collatinus] complura (#52) 



The usual plural form of complures is complura , but this form is not recognized by Collatinus .
