### ISSUE TITLE
Source of truth for Collatinus data files (particularly lemmes.la)?

### ISSUE THREAD

**Issue by ghost** [biblissima/collatinus#60]
Hi, I wanted to be sure that I contribute to the main `lemmes.la` file when I do contribute. I see there's a few branches in this repo, and I see variations and forks of this project, e.g. `gocol`. https://github.com/ycollatin/gocol/issues/1

Should I treat the `master` branch of `biblissima/collatinus` as the source of truth for all the data files?

Thanks! Just double-checking...

**Comment by ycollatin** [comment]
Hi Thomas,
Le 5 mai 2020, à 18h21, Thomas Klemz écrivit :
>Hi, I wanted to be sure that I contribute to the main `lemmes.la`
>file when I do contribute. I see there's a few branches in this repo,
>and I see variations and forks of this project, e.g. `gocol`.
>https://github.com/ycollatin/gocol/issues/1

    ycollatin is a repo I use for some experimental developments.
Gocol is a Collatinus fork written in Go as a package to be included
in other applications. I am using it for /Gentes/, a syntax analyzer
https://github.com/ycollatin/gentes (in alpha version).

>Should I treat the `master` branch of `biblissima/collatinus` as the
>source of truth for all the data files?

    The lemmes.la of gocol is only in french, and I have done a lot of
changes on it. Don't bother with that. Best regards.
-- 
                                                       Yves

**Comment by PhVerkerk** [comment]
Checked also in Medieval which is the branch I am working on.
