### ISSUE TITLE
Format of .col files

### ISSUE THREAD

**Issue by nivaca** [biblissima/collatinus#64]
Hi,
I would like to decompress the `.col` files (the dictionaries), but I have not found the proper format they are in. Could you please help me with that? 
Thanks.
Nicolas Vaughan

**Comment by PhVerkerk** [comment]
Dear Nicolas,

The .col files are in a strange binary format that contains strings
compressed and decompressed using Qt qCompress and qUncompress
functions. I can't tell you more about these functions, except that they
are zip-like but not zip-compatible.

Why do you want/need to decompress the .col files ?

Yours,

    Philippe.

Le 01/04/2021 à 18:17, Nicolas Vaughan a écrit :

**Comment by nivaca** [comment]
Dear Phillipe,
Thanks for your reply. I would like to have direct access to the dictionary contents.
Best wishes,
Nicolas

**Comment by ycollatin** [comment]
Hi all,
Le 1 avril 2021, à 09h40, Nicolas Vaughan écrivit :
>Thanks for your reply. I would like to have direct access to the dictionary contents.
>Best wishes,

    A good manner to do that is to install Collatinus, and then to
pick the dictionaries you need in .../directory_where_is_collatinus/data/lemmes.* 
Cheers,
-- 
                       Yves Ouvrard

**Comment by nivaca** [comment]
Hi Yves,
Thanks for your suggestion. It worked fine.

**Edit:**
However, I now get a some `.cz` files which are still compressed and hence inaccessible.

Best,
Nicolas

**Comment by PhVerkerk** [comment]
I assume that you have the same problem with the .cz format (c for
Collatinus and z for Zipped, but with Qt qCompress). The underlying
string-format is HTML but the information is the same as the original
TeX (for Gaffiot) or XML (for L&S) files, which are available in
different places :
- http://gerardgreco.free.fr/spip.php?article47
- https://github.com/helmadik/LewisShortLogeion
The Lewis&Short comes from Perseus with the original funny name
"1999.04.0059.xml". But the Logeion version has been improved by Helma
Dik. The version in Collatinus has been corrected independently and it
would be interesting to collect both sets of corrections (but the direct
comparison cannot be made automatically). If you are interested, let me
know (out of github comments would be better). Just to give figures :
the comparison of the letter "A" took me about one month (July 2020,
resulting in corrections that are not yet in Collatinus).

The recently added dictionaries are available on the web :
- Jeanneau : http://www.prima-elementa.fr/Dico.htm
- Ramminger : http://nlw.renaessancestudier.org/words/start.htm
- Köbler : http://www.koeblergerhard.de/Mittellatein-HP/VorwortMlat-HP.htm

Yours,

    Philippe.

Le 01/04/2021 à 19:48, Nicolas Vaughan a écrit :

**Comment by nivaca** [comment]
Dear Phillipe,

Thanks for your message. The XML version of the L&S was very interesting.
I was also interested in the Ramminger, but I found no downloadable version in the web page you mentioned.

All best,

Nicolas

**Comment by PhVerkerk** [comment]
It's right : I have a collection of 21,115 files. I try to change my
program to produce a readable HTML file.

Philippe.

Le 02/04/2021 à 15:38, Nicolas Vaughan a écrit :

**Comment by PhVerkerk** [comment]
You'll find the HTML version of Ramminger's dictionary there :
https://filesender.renater.fr/?s=download&token=7fa545bc-a3a0-45c2-97a5-47599c157db0

As Collatinus does not need the alphabetical order (in the file of the
dictionary), the lemmata come as they are in the numbered original
files. I have to change dramatically my program to order the entries, so
I hope it is fine for you. If needed, you can find the alphabetically
ordered list of the entries in the first column of
Ramminger_2020-jan20.idx you have in Collatinus (copy it, rename it .csv
and open it with LibreOffice for instance, the ":" is the column separator).

Yours,

    Philippe.

Le 02/04/2021 à 15:38, Nicolas Vaughan a écrit :

**Comment by nivaca** [comment]
Dear Philippe,

You are very kind!

All best wishes,
   Nicolas
