### ISSUE TITLE
duplications de mots inutiles dans lemmes.la

### ISSUE THREAD

**Issue by mcorne** [biblissima/collatinus#66]
les duplications de mots suivantes semblent inutiles dans lemmes.la :
```
dĭpundius=dĭpūndĭus,dĭpūndĭus|filius|||i, m.|1
Tmōlus=Tmōlus,Tmōlus|lupus|||i, m.|7
vulnus=vūlnŭs,vūlnŭs|corpus|vūlnĕr,vōlnĕr||ĕris, n.|400
```
on les trouvent avec le motif de recherche `\w+=(\w+),\1\b`

**Comment by PhVerkerk** [comment]
Bonjour,

Je m'en vais corriger ça. Ce ne sont pas des doublons à supprimer, mais
à corriger (lapsus calami)

|dĭpundius=dĭpūndĭus,d|||ŭ|p|||ō|ndĭus|filius|||i, m.|1 Tmōlus=Tmōlus,T|||ĭ|mōlus|lupus|||i, m.|7 vulnus=vūlnŭs,v|||ō|lnŭs|corpus|vūlnĕr,vōlnĕr||ĕris, n.|400 |

Philippe.


Le 12/09/2021 à 12:44, Michel Corne a écrit :

**Comment by PhVerkerk** [comment]
2022/02/02 Vérifié dans la branche Medieval
